### ISSUE TITLE
No record found

### ISSUE THREAD

**Issue by greenozon** [herosi/classinformer-ida8#5]
I'm trying to detect some classes inside the windows standard dll - evr.dll
but seems it can't find anything (exception init tables)

also, is the message
```
  ** arguments not located!
```

good one?

eg:

```
>> Class Informer: v: 2.9, built: Aug 21 2024, By Rohitab Batra (by Hiroshi Suzuki, Sirmabus originally)
Working..

Processing C/C++ ctor & dtor tables..
-------------------------------------------------
000000006CC2C4D6 I: "__initterm", 6 bytes.
000000006CC2CFD1 E: "__initterm_e", 36 bytes.
 
000000006CC2C4D6 processInitterm: "__initterm" 
  000000006CC2D8D3 "__initterm" xref.
  000000006CC2D8C9 Two instruction pattern match #0
    000000006CC2D90C to 000000006CC2D960 CTOR/DTOR table.
 
000000006CC2CFD1 processInitterm: "__initterm_e" 
  000000006CC2D8BE "__initterm_e" xref.
  ** arguments not located!
 
Processing time: 0.25 seconds.

Scanning for for RTTI Complete Object Locators..
-------------------------------------------------
 N: ".data", A: 000000006CC82000 - 000000006CC84000, S: 8 KB.
     Total COL: 0
COL scan time: 0.001

Scanning for Virtual Function Tables..
-------------------------------------------------
 N: ".data", A: 000000006CC82000 - 000000006CC84000, S: 8 KB.
Vftable scan time: 0.001
 

=========== Stats ===========
  RTTI vftables: 0
Processing time: 0.25 seconds
Done.
```

I"m using build by @rohitab  inside Ida9 beta

**Comment by rohitab** [comment]
@greenozon It looks like `evr.dll` does not have RTTI information, except for a single entry for `RTTI Complete Object Locator`.

**Comment by herosi** [comment]
First, you should post the issue on his repository because it:s not mine.
Second, you should understand how classinformer works. It completely relies on the RTTI but it seems the DLL does not have RTTI. You should check it before asking to the author.

**Comment by greenozon** [comment]
Thank you for kind update @herosi  and sorry for confusion
for some reason the forked GH repo does not have the "Issues" feature, so that's why I put the disturbing question here

2) on RTTI - well, the thing is that in runtime this evr.dll throws an exception  about RTTI, but of course it's not the issue of the plugin

good luck
